[package]
name = "easy_sermon"
version = "1.2.5"
edition = "2021"
authors = [
    "Christian Mbaba <Mxlightningx@gmail.com>",
    "Dominion Chapel Houston <media@dominionchapel.org>",
]

[dependencies]
idna = "1.0.3"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }

[dev-dependencies]
idna = "1.0.3"
