name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt
          profile: minimal

      - name: Build
        run: cargo build --release
      
      - name: Lint
        run: cargo clippy --release -- -D warnings
      
      - name: Test
        run: cargo test --release
      