name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt
          profile: minimal
        
      - name: Unix Deps
        run: sudo apt-get install libasound2-dev libavdevice-dev libavfilter-dev libavutil-dev # libsdl2-dev libavcodec-dev libavformat-dev

      - name: Build
        run: cargo build --release
      
      - name: Lint
        run: cargo clippy --release -- -D warnings
      
      - name: Test
        run: cargo test --release
      
      - name: Pythonv3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
      