on: push
name: EasySermon

env:
  # RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings, including Clippy lints
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      
      - name: Run Linter
        run: cargo clippy --all-targets --all-features
      
      - name: Run tests
        run: cargo test
      